name: google_cloud_logging
description: >-
  Structured logging for Google Cloud environments with trace correlation
  and automatic formatting.
version: 0.5.0
repository: https://github.com/googleapis/google-cloud-dart/tree/main/pkgs/google_cloud_logging

resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  google_cloud_logging_type: ^0.5.2
  google_cloud_logging_v2: ^0.5.2
  google_cloud_protobuf: ^0.5.2
  meta: ^1.18.2
  stack_trace: ^1.11.0

dev_dependencies:
  test: ^1.31.0
