name: google_cloud_logging
version: 0.5.0-wip
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  google_cloud_logging_type: ^0.5.2
  google_cloud_logging_v2: ^0.5.2
  google_cloud_protobuf: ^0.5.2
  stack_trace: ^1.11.0

dev_dependencies:
  test: ^1.31.0
