name: google_cloud_shelf
version: 0.6.0-wip
description: >-
  Shelf middleware for Google Cloud environments providing structured
  logging, trace correlation, exception mapping, and graceful shutdown
  orchestration.
repository: https://github.com/googleapis/google-cloud-dart/tree/main/pkgs/google_cloud_shelf

resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  google_cloud_logging: ^0.6.0-wip
  http: ^1.6.0
  meta: ^1.18.2
  shelf: ^1.4.2
  stack_trace: ^1.12.1

dev_dependencies:
  test: ^1.31.0
  test_process: ^2.0.3
