# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

permissions: read-all

# Run on PRs and pushes to the default branch.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# We use a specific Dart SDK version here in order to have hermetic,
# reproducable builds (formatting can change between SDK versions, ...).
env:
  DART_VERSION: 3.9.2
  GOOGLE_CLOUD_PROJECT: test-project
  LIBRARIAN_VERSION: v0.21.0
  GOTOOLCHAIN: go1.26.4
name: Dart Checks
jobs:
  analyze_and_format:
    name: Analyze and Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: dart-lang/setup-dart@65eb853c7ba17dde3be364c3d2858773e7144260
        with:
          sdk: ${{ env.DART_VERSION }}
      - name: Cache Pub Dependencies
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-
      - run: dart pub get
      - name: Analyze
        run: dart analyze
      - name: Format
        run: dart format --output=none --set-exit-if-changed .
      - name: Verify Code Excerpts Up-to-Date
        run: dart run tool/update_excerpts.dart --fail-on-update

  analyze_dev:
    name: Analyze (dev SDK)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: dart-lang/setup-dart@65eb853c7ba17dde3be364c3d2858773e7144260
        with:
          sdk: dev
      - name: Cache Pub Dependencies
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-dev-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-dev-
      - run: dart pub get
      - name: Analyze
        run: dart analyze --fatal-infos

  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ["chrome", "vm"]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: dart-lang/setup-dart@65eb853c7ba17dde3be364c3d2858773e7144260
        with:
          sdk: ${{ env.DART_VERSION }}
      - run: dart pub get
      - run: dart test -p ${{ matrix.platform }} .

  storage_testbench_tests:
    name: Storage Testbench Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: dart-lang/setup-dart@65eb853c7ba17dde3be364c3d2858773e7144260
        with:
          sdk: ${{ env.DART_VERSION }}
      - run: dart pub get
      - run: docker run -d --rm -p 9000:9000 -p 8888:8888 gcr.io/cloud-devrel-public-resources/storage-testbench:latest
      - run: dart test -P storage-testbench .

  firestore_emulator_tests:
    name: Firestore Emulator Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
      - uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520
        with:
          distribution: 'zulu'
          java-version: '25'
      - uses: dart-lang/setup-dart@65eb853c7ba17dde3be364c3d2858773e7144260
        with:
          sdk: ${{ env.DART_VERSION }}
      - run: dart pub get
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Run Tests
        run: firebase emulators:exec --config=firestore_emulators/firebase.json \
          "dart test -P firebase-emulator ."

  generator:
    name: Generators
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: Install protoc
        run: |
          set -e
          curl -fSSL  --retry 3 --retry-all-errors --retry-delay 15 -o /tmp/protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v28.3/protoc-28.3-linux-x86_64.zip
          cd /usr/local
          sudo unzip -x /tmp/protoc.zip
          protoc --version
      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16
        with:
          go-version: 1.26.1
          cache: false
      - name: Cache Go Librarian
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-librarian-${{ env.LIBRARIAN_VERSION }}
      - name: Install Dart  # The generator uses "dart format".
        uses: dart-lang/setup-dart@65eb853c7ba17dde3be364c3d2858773e7144260
        with:
          sdk: ${{ env.DART_VERSION }}
      - run: dart pub get
      # Regenerate and check the existing clients. If there is any difference
      # between the generated code and the committed code that is an error; all
      # the inputs should be pinned, including the generator version and the
      # googleapis SHA.
      - name: Regenerate existing clients
        # The current head version of librarian can be generated with:
        # GOPROXY=direct go list -m -u -f '{{.Version}}' github.com/googleapis/librarian@main
        run: go run github.com/googleapis/librarian/cmd/librarian@${{ env.LIBRARIAN_VERSION }} generate -all
      - name: Format librarian configuration
        run: go run github.com/googleapis/librarian/cmd/librarian@${{ env.LIBRARIAN_VERSION }} tidy
      - name: Update documentation
        run: dart run tool/update_docs.dart
      - name: Generated Diff
        run: git diff --exit-code
      - name: Print diff on failure
        if: failure()
        run: git diff

